### ISSUE TITLE
bail on specific on_retry E types

### ISSUE THREAD

**Issue by alekspickle** [EmbarkStudios/tryhard#26]
**Is your feature request related to a problem? Please describe.**
I am trying to construct a retry function that is used for all requests in my app, so I am dealing with pretty hairy generic errors.
So let's say I want only request be retried on a specific errors, right now there is no way doing that.
I tried to provide this function with a way to override all relevant input params but I am unsusccesful in doing that with on_retry. This is touching pretty some pretty ugly async insides.

**Describe the solution you'd like**
This is basically what I would've like to work:

```

use std::{fmt::Display, future::Future};
use tokio::time::Duration;

const RETRIES: u32 = 6;
const BACKOFF_STEP: Duration = Duration::from_secs(1);
const MAX_DELAY: Duration = Duration::from_secs(10);

type OnRetry<T, E> =
    Box<dyn Fn(u32, Option<Duration>, &'static E) -> dyn Future<Output = Result<T, E>>>;

///
/// impl FnMut() -> F is a bound of [`tryhard::retry_fn`]
///
pub(crate) async fn retry_fn<F, T, E>(opts: Opts<T, E>, task: impl FnMut() -> F) -> Result<T, E>
where
    E: Display + Send + 'static,
    F: Future<Output = Result<T, E>>,
{
    tryhard::retry_fn(task)
        .retries(opts.retries)
        .exponential_backoff(opts.backoff_step)
        .max_delay(opts.max_delay)
        .on_retry(opts.on_retry)
        .await
}

pub struct Opts<T: 'static, E: Display + 'static> {
    retries: u32,
    backoff_step: Duration,
    max_delay: Duration,
    on_retry: OnRetry<T, E>,
}

impl<T, E: Display> Opts<T, E> {
    fn new() -> Self {
        let on_retry = |attempt, _, error: &E| {
            let error = error.to_string();
            async move {
                tracing::warn!(%attempt, %error, "async task error, retrying...");
                Ok::<(), E>(())
            }
        };
        Self {
            retries: RETRIES,
            backoff_step: BACKOFF_STEP,
            max_delay: MAX_DELAY,
            on_retry: Box::new(on_retry),
        }
    }
    pub fn with_retries(mut self, retries: u32) -> Self {
        self.retries = retries;
        self
    }
    pub fn with_backoff_step(mut self, backoff_step: Duration) -> Self {
        self.backoff_step = backoff_step;
        self
    }
    pub fn with_max_delay(mut self, max_delay: Duration) -> Self {
        self.max_delay = max_delay;
        self
    }

    pub fn with_on_retry(mut self, on_retry: OnRetry<T, E>) -> Self {
        self.on_retry = on_retry;
        self
    }
}




```

**Describe alternatives you've considered**
I don't see any alternatives to this, I took a look to a crate code but found no easy way of doing this

**Additional context**
Is this possible to do in a current state? If not, It makes sense to have something like `do_not_retry_on/stop_on`

**Comment by davidpdrsn** [comment]
Thats not really possible using rust generics. You can't really (without hacks) which type a type parameter actually is. I'd recommend you just make different retry functions with the different configs that you need. I think trying to make just one function is overcomplicating it.
