### ISSUE TITLE
Add closure to determine which errors should be retried

### ISSUE THREAD

**Issue by pronebird** [EmbarkStudios/tryhard#28]
**Is your feature request related to a problem? Please describe.**

`tryhard::retry_fn()` would keep retrying for as long as it receives an `Error` and until it runs out of retry attempts. However it may not make sense to continue retrying if the returned error indicates that it cannot be recovered from by simply trying again.
 
**Describe the solution you'd like**
I'd like to have a helper method that takes an argument `Fn(&E) -> bool` that when evaluated to `false` would stop the retry logic and return the last received error to the caller.

**Describe alternatives you've considered**

**Additional context**

**Comment by pronebird** [comment]
@davidpdrsn appreciate it, however I think that ergonomics could be improved, considering that I don't need custom backoff, for example my current approach looks as such:

```

**Comment by davidpdrsn** [comment]
I don't think its too bad.
